### ISSUE TITLE
Allowing specification of the download directory

### ISSUE THREAD

**Issue by CMCDragonkai** [datapythonista/mnist#9]
Right now the functions listed on the README.md doesn't allow specifying the target directory. This functionality should be possible just by propagating extra parameters to the download function.

**Comment by datapythonista** [comment]
I'd prefer to keep the API as simple as possible.

I think I'd prefer to have a function `temporary_dir` that can be changed by the user:

```
import mnist

mnist.temporary_dir = lambda: '/home/myuser/'

train_images = mnist.train_images()
train_labels = mnist.train_labels()
```

I find this better than what I think you're proposing:

```
import mnist

train_images = mnist.train_images('/home/myuser/')
train_labels = mnist.train_labels('/home/myuser/')
```

What do you think? Do you want to send a pull request?
